-- Crear la tabla de marcadores (bookmarks)
create table bookmarks (
  id bigint generated by default as identity primary key,
  title text not null,
  url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS (Row Level Security) - Opcional, pero recomendado
-- Si deseas permitir lectura/escritura pública por simplicidad de este demo:
alter table bookmarks enable row level security;

create policy "Permitir lectura pública"
on bookmarks for select
to anon
using (true);

create policy "Permitir inserción pública"
on bookmarks for insert
to anon
with check (true);

create policy "Permitir borrado público"
on bookmarks for delete
to anon
using (true);
